# Generated by Django 5.0 on 2023-12-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComputerName', models.CharField(max_length=255)),
                ('Brand', models.CharField(max_length=255)),
                ('CPU', models.CharField(max_length=255)),
                ('GPU', models.CharField(max_length=255)),
                ('PublicDate', models.DateField(null=True)),
                ('Ram', models.IntegerField(null=True)),
                ('RamType', models.IntegerField(null=True)),
                ('Size', models.FloatField(null=True)),
                ('Price', models.IntegerField(null=True)),
            ],
        ),
    ]
