# Generated by Django 4.2.7 on 2023-12-12 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_brandtype_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPUType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='computer',
            name='Brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.brandtype'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='GPU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.gputype'),
        ),
    ]
