# Generated by Django 4.2.7 on 2023-12-12 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_gputype_alter_computer_brand_alter_computer_gpu'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GPUBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='computer',
            name='Brand',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='computer',
            name='CPU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.cputype'),
        ),
    ]
