# Generated by Django 4.2.7 on 2023-12-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_computer_cpu_alter_computer_gpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='Brand',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='CPU',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='GPU',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
