# Generated by Django 4.2.7 on 2023-12-12 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_computer_brand_alter_computer_cpu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='Brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.brandtype'),
        ),
    ]
