# Generated by Django 5.0 on 2023-12-26 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_gputype_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='GPU',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='RamType',
        ),
        migrations.AddField(
            model_name='computer',
            name='GPUBrands',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.gpubrands'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='CPU',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.cputype'),
        ),
    ]
